### ISSUE TITLE
Support for LittleFS

### ISSUE THREAD

**Issue by rvdbreemen** [kash4kev/vscode-esp8266fs#17]
As SPIFFS is being depricated by the core dev of ESP8266 and moved over to LittleFS. Is it possible to support this with this plugin? Or did I just not look hard enough?

**Comment by InnuendoPi** [comment]
You may try my mod https://github.com/InnuendoPi/vscode-esp8266fs
Use it as is, modify as you want. Only tested with ESP8266 yet.

**Comment by renatoaloi** [comment]
Working on it!
https://github.com/renatoaloi/vscode-esp8266littlefs
